package compiler

import (
	"bytes"
	"os"
	"path/filepath"
	"reflect"
	"testing"

	"github.com/alexei-led/agentbundler/internal/compiler/model"
)

func TestAntigravityConductorExampleBuildCheckAndNativeDeclaration(t *testing.T) {
	firstRoot, manifest, first := compileAntigravityConductorExample(t)
	secondRoot, _, second := compileAntigravityConductorExample(t)
	if !reflect.DeepEqual(first.Plan, second.Plan) {
		t.Fatal("Conductor example plans differ across absolute workspace roots")
	}
	for _, file := range first.Plan.CompilerFiles {
		if bytes.Contains(file.Bytes, []byte(firstRoot)) || bytes.Contains(file.Bytes, []byte(secondRoot)) {
			t.Fatal("Conductor example provenance contains an absolute workspace root")
		}
	}

	if len(first.Plan.Targets) != 1 || first.Plan.Targets[0].Target != model.TargetAntigravity {
		t.Fatalf("Conductor example targets = %#v", first.Plan.Targets)
	}
	plan := first.Plan.Targets[0]
	wantBytes := map[model.RelativePath]string{
		"README.md":                       "# conductor-example\n\nPlan and execute a small change with explicit checkpoints\n\nGenerated by **Agent Bundler**.\n",
		"plugin.json":                     `{"description":"Plan and execute a small change with explicit checkpoints","name":"conductor-example"}` + "\n",
		"rules/conductor_antigravity.md":  "---\ntrigger: model_decision\n---\n\n# Keep the plan visible\n\nWhen implementation has multiple checkpoints, state the active checkpoint before\nediting. Verify it before moving on. If a blocker changes the requested scope,\nstop and explain the blocker instead of silently changing the plan.\n",
		"skills/conductor-setup/SKILL.md": "---\n{\"description\":\"Set up a small, verifiable implementation plan.\",\"metadata\":{\"version\":\"0.1.0\"},\"name\":\"conductor-setup\"}\n---\n\n# Set up a conductor-style plan\n\n1. Restate the requested outcome and constraints.\n2. Split the work into checkpoints with one verification command each.\n3. Complete checkpoints in order and report any blocker before changing scope.\n",
	}
	if got, want := targetPaths(plan), sortedMapPaths(wantBytes); !reflect.DeepEqual(got, want) {
		t.Fatalf("Conductor example paths = %#v, want %#v", got, want)
	}
	for _, file := range plan.Files {
		if got, want := string(file.Bytes), wantBytes[file.Path]; got != want {
			t.Errorf("Conductor example file %q = %q, want %q", file.Path, got, want)
		}
	}
	if len(plan.NativeChecks) != 1 {
		t.Fatalf("Conductor example native checks = %#v", plan.NativeChecks)
	}
	check := plan.NativeChecks[0]
	if check.Program != "agy" || !reflect.DeepEqual(check.Arguments, []string{"plugin", "validate", "."}) || check.WorkingDirectory != nil || check.Location.Path != "internal/target/antigravity/antigravity.go" {
		t.Fatalf("Conductor example native check = %#v", check)
	}

	outputRoot := filepath.Join(firstRoot, "generated")
	before := snapshotTree(t, outputRoot)
	checked := Compile(CompileRequest{WorkspaceRoot: firstRoot, Manifest: manifest, Mode: BuildModeCheck})
	if len(checked.Diagnostics) != 0 || checked.Drift || checked.NativeVerificationFailed {
		t.Fatalf("Conductor example check = %#v", checked)
	}
	if after := snapshotTree(t, outputRoot); !reflect.DeepEqual(after, before) {
		t.Fatal("Conductor example check changed generated output")
	}
}

func compileAntigravityConductorExample(t *testing.T) (string, model.SourceManifest, CompilationResult) {
	t.Helper()
	workspace := t.TempDir()
	fixture := filepath.Join("..", "..", "examples", "antigravity-conductor")
	if err := os.CopyFS(workspace, os.DirFS(fixture)); err != nil {
		t.Fatalf("copy Antigravity Conductor example: %v", err)
	}
	data, err := os.ReadFile(filepath.Join(workspace, "agentbundle.json"))
	if err != nil {
		t.Fatal(err)
	}
	manifest, diagnostics := model.DecodeSourceManifestJSON(data)
	if len(diagnostics) != 0 {
		t.Fatalf("decode Antigravity Conductor example manifest: %#v", diagnostics)
	}
	result := Compile(CompileRequest{WorkspaceRoot: filepath.Clean(workspace), Manifest: manifest, Mode: BuildModeBuild})
	if len(result.Diagnostics) != 0 {
		t.Fatalf("compile Antigravity Conductor example: %#v", result.Diagnostics)
	}
	return workspace, manifest, result
}
