package compiler

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"os"
	"os/exec"
	"path/filepath"
	"reflect"
	"sort"
	"strings"
	"testing"
	"time"

	"github.com/alexei-led/agentbundler/internal/compiler/model"
)

const claudeProtocolOutputLimit = 1024

func TestCompileClaudeHooksEndToEndIsDeterministic(t *testing.T) {
	firstRoot, first := compileClaudeHookFixture(t)
	secondRoot, second := compileClaudeHookFixture(t)
	if !reflect.DeepEqual(first.Plan, second.Plan) {
		t.Fatal("Compile() plans differ across absolute workspace roots")
	}
	if bytes.Contains(first.Plan.CompilerFiles[0].Bytes, []byte(firstRoot)) || bytes.Contains(first.Plan.CompilerFiles[0].Bytes, []byte(secondRoot)) {
		t.Fatal("provenance contains an absolute workspace root")
	}

	if len(first.Plan.Targets) != 1 || first.Plan.Targets[0].Target != model.TargetClaude {
		t.Fatalf("Compile() target plan = %#v", first.Plan.Targets)
	}
	plan := first.Plan.Targets[0]
	wantBytes := map[model.RelativePath]string{
		".claude-plugin/plugin.json": `{"$schema":"https://json.schemastore.org/claude-code-plugin-manifest.json","author":{"name":"Agent Bundler"},"description":"Hermetic Claude passive hook fixture","name":"protocol-hooks","version":"1.0.0"}` + "\n",
		"README.md":                  "# protocol-hooks\n\nHermetic Claude passive hook fixture\n\nGenerated by **Agent Bundler**.\n",
		"hooks/hooks.json":           `{"hooks":{"PreToolUse":[{"matcher":"Bash","hooks":[{"type":"command","command":"python3","args":["${CLAUDE_PLUGIN_ROOT}/hooks/allow/protocol.py","allow"],"timeout":2}]}]}}` + "\n",
	}
	script, err := os.ReadFile(filepath.Join("testdata", "hooks-claude", "source", "src", "hooks", "allow", "protocol.py"))
	if err != nil {
		t.Fatal(err)
	}
	wantBytes["hooks/allow/protocol.py"] = string(script)
	if got, want := targetPaths(plan), sortedMapPaths(wantBytes); !reflect.DeepEqual(got, want) {
		t.Fatalf("generated paths = %#v, want %#v", got, want)
	}
	for _, file := range plan.Files {
		if got := string(file.Bytes); got != wantBytes[file.Path] {
			t.Errorf("generated bytes for %q = %q, want %q", file.Path, got, wantBytes[file.Path])
		}
		if file.Executable {
			t.Errorf("interpreter-backed file %q unexpectedly requires executable intent", file.Path)
		}
		wantOrigin := expectedClaudeFixtureOrigin(file.Path)
		if !reflect.DeepEqual(file.Origin, wantOrigin) {
			t.Errorf("origin for %q = %#v, want %#v", file.Path, file.Origin, wantOrigin)
		}
	}
	assertClaudeFixtureProvenance(t, first.Plan.CompilerFiles, sortedMapPaths(wantBytes))

	python, err := exec.LookPath("python3")
	if err != nil {
		t.Skipf("interpreter-backed fixture unavailable: python3 is not on PATH: %v", err)
	}
	request := []byte(`{"session_id":"fixture","hook_event_name":"PreToolUse","tool_name":"Bash","tool_input":{"command":"rm -rf /tmp/example"}}`)
	path := filepath.Join(firstRoot, "generated", "claude", "hooks", "allow", "protocol.py")
	result := runClaudeProtocol(t, 2*time.Second, claudeProtocolOutputLimit, request, python, path, "allow")
	want := `{"hookSpecificOutput":{"hookEventName":"PreToolUse","permissionDecision":"allow"}}` + "\n"
	if result.timedOut || result.exitCode != 0 || result.stdoutLimited || result.stderrLimited || string(result.stdout) != want || len(result.stderr) != 0 {
		t.Fatalf("protocol result = %#v, want stdout %q", result, want)
	}
}

func TestCompileClaudeTranslatesDecisionHooks(t *testing.T) {
	workspace := t.TempDir()
	if err := os.CopyFS(workspace, os.DirFS(filepath.Join("testdata", "hooks-claude"))); err != nil {
		t.Fatalf("copy fixture: %v", err)
	}
	packagePath := filepath.Join(workspace, "source", "packages", "hooks.json")
	data := []byte(`{"id":"protocol-hooks","metadata":{"version":"1.0.0","description":"Decision hooks","author":"Agent Bundler"},"assets":["src/hooks/deny","src/hooks/rewrite"]}`)
	if err := os.WriteFile(packagePath, data, 0o644); err != nil {
		t.Fatal(err)
	}
	manifestData, err := os.ReadFile(filepath.Join(workspace, "agentbundle.json"))
	if err != nil {
		t.Fatal(err)
	}
	manifest, diagnostics := model.DecodeSourceManifestJSON(manifestData)
	if len(diagnostics) != 0 {
		t.Fatalf("DecodeSourceManifestJSON() diagnostics = %#v", diagnostics)
	}
	result := Compile(CompileRequest{WorkspaceRoot: filepath.Clean(workspace), Manifest: manifest, Mode: BuildModeBuild})
	if len(result.Diagnostics) != 0 {
		t.Fatalf("Compile() diagnostics = %#v", result.Diagnostics)
	}
	if len(result.Plan.Targets) != 1 {
		t.Fatalf("Compile() targets = %#v", result.Plan.Targets)
	}
	hooks := ""
	for _, file := range result.Plan.Targets[0].Files {
		if file.Path == "hooks/hooks.json" {
			hooks = string(file.Bytes)
		}
	}
	for _, identity := range []string{"hook/deny", "hook/rewrite"} {
		if !strings.Contains(hooks, identity) {
			t.Fatalf("translated hooks missing %q: %s", identity, hooks)
		}
	}
	if !strings.Contains(hooks, "node") || !strings.Contains(hooks, "permissionDecision") {
		t.Fatalf("translated hooks do not contain Claude decision adapter: %s", hooks)
	}
}

func TestClaudeHookSubprocessHarnessBoundsProtocolFailures(t *testing.T) {
	root, _ := compileClaudeHookFixture(t)
	python, err := exec.LookPath("python3")
	if err != nil {
		t.Skipf("interpreter-backed fixture unavailable: python3 is not on PATH: %v", err)
	}
	script := filepath.Join(root, "generated", "claude", "hooks", "allow", "protocol.py")

	exited := runClaudeProtocol(t, time.Second, claudeProtocolOutputLimit, nil, python, script, "exit")
	if exited.exitCode != 23 || string(exited.stderr) != "fixture exit\n" || exited.timedOut {
		t.Fatalf("exit result = %#v", exited)
	}

	timedOut := runClaudeProtocol(t, 50*time.Millisecond, claudeProtocolOutputLimit, nil, python, script, "sleep")
	if !timedOut.timedOut || timedOut.exitCode != -1 {
		t.Fatalf("timeout result = %#v", timedOut)
	}

	limited := runClaudeProtocol(t, time.Second, 128, nil, python, script, "flood")
	if limited.exitCode != 0 || !limited.stdoutLimited || !limited.stderrLimited || len(limited.stdout) != 128 || len(limited.stderr) != 128 {
		t.Fatalf("output-limit result = %#v", limited)
	}
}

type claudeProtocolResult struct {
	stdout        []byte
	stderr        []byte
	exitCode      int
	timedOut      bool
	stdoutLimited bool
	stderrLimited bool
}

func runClaudeProtocol(t *testing.T, timeout time.Duration, limit int, stdin []byte, program string, arguments ...string) claudeProtocolResult {
	t.Helper()
	ctx, cancel := context.WithTimeout(context.Background(), timeout)
	defer cancel()
	command := exec.CommandContext(ctx, program, arguments...)
	command.Stdin = bytes.NewReader(stdin)
	stdout := &boundedTestBuffer{limit: limit}
	stderr := &boundedTestBuffer{limit: limit}
	command.Stdout = stdout
	command.Stderr = stderr
	err := command.Run()
	result := claudeProtocolResult{
		stdout: append([]byte(nil), stdout.Bytes()...), stderr: append([]byte(nil), stderr.Bytes()...),
		exitCode: 0, timedOut: errors.Is(ctx.Err(), context.DeadlineExceeded),
		stdoutLimited: stdout.limited, stderrLimited: stderr.limited,
	}
	if result.timedOut {
		result.exitCode = -1
	} else if err != nil {
		var exitError *exec.ExitError
		if !errors.As(err, &exitError) {
			t.Fatalf("run protocol: %v", err)
		}
		result.exitCode = exitError.ExitCode()
	}
	return result
}

type boundedTestBuffer struct {
	data    bytes.Buffer
	limit   int
	limited bool
}

func (buffer *boundedTestBuffer) Write(value []byte) (int, error) {
	originalLength := len(value)
	remaining := buffer.limit - buffer.data.Len()
	if remaining < len(value) {
		buffer.limited = true
		if remaining < 0 {
			remaining = 0
		}
		value = value[:remaining]
	}
	_, _ = buffer.data.Write(value)
	return originalLength, nil
}

func (buffer *boundedTestBuffer) Bytes() []byte { return buffer.data.Bytes() }

func compileClaudeHookFixture(t *testing.T) (string, CompilationResult) {
	t.Helper()
	workspace := t.TempDir()
	if err := os.CopyFS(workspace, os.DirFS(filepath.Join("testdata", "hooks-claude"))); err != nil {
		t.Fatalf("copy fixture: %v", err)
	}
	data, err := os.ReadFile(filepath.Join(workspace, "agentbundle.json"))
	if err != nil {
		t.Fatal(err)
	}
	manifest, diagnostics := model.DecodeSourceManifestJSON(data)
	if len(diagnostics) != 0 {
		t.Fatalf("DecodeSourceManifestJSON() diagnostics = %#v", diagnostics)
	}
	result := Compile(CompileRequest{WorkspaceRoot: filepath.Clean(workspace), Manifest: manifest, Mode: BuildModeBuild})
	if len(result.Diagnostics) != 0 {
		t.Fatalf("Compile() diagnostics = %#v", result.Diagnostics)
	}
	return workspace, result
}

func targetPaths(plan model.TargetPlan) []model.RelativePath {
	paths := make([]model.RelativePath, len(plan.Files))
	for index, file := range plan.Files {
		paths[index] = file.Path
	}
	return paths
}

func sortedMapPaths(files map[model.RelativePath]string) []model.RelativePath {
	paths := make([]model.RelativePath, 0, len(files))
	for path := range files {
		paths = append(paths, path)
	}
	sort.Slice(paths, func(i, j int) bool { return paths[i] < paths[j] })
	return paths
}

func expectedClaudeFixtureOrigin(path model.RelativePath) []model.SourceLocation {
	switch path {
	case "hooks/allow/protocol.py":
		return []model.SourceLocation{{Path: "src/hooks/allow/protocol.py"}}
	case "hooks/hooks.json":
		return []model.SourceLocation{{Path: "src/hooks/allow/hook.json"}}
	default:
		return nil
	}
}

func assertClaudeFixtureProvenance(t *testing.T, files []model.PlannedFile, wantPaths []model.RelativePath) {
	t.Helper()
	if len(files) != 1 || files[0].Path != ".agentbundler/build.json" || files[0].Executable || len(files[0].Origin) != 0 {
		t.Fatalf("compiler files = %#v", files)
	}
	var document struct {
		Outputs []struct {
			Target string `json:"target"`
			Files  []struct {
				Path       string `json:"path"`
				Executable bool   `json:"executable"`
			} `json:"files"`
		} `json:"outputs"`
	}
	if err := json.Unmarshal(files[0].Bytes, &document); err != nil {
		t.Fatal(err)
	}
	if len(document.Outputs) != 1 || document.Outputs[0].Target != "claude" {
		t.Fatalf("provenance outputs = %#v", document.Outputs)
	}
	gotPaths := make([]model.RelativePath, len(document.Outputs[0].Files))
	for index, file := range document.Outputs[0].Files {
		gotPaths[index] = model.RelativePath(file.Path)
		if file.Executable {
			t.Errorf("provenance marks %q executable", file.Path)
		}
	}
	if !reflect.DeepEqual(gotPaths, wantPaths) {
		t.Fatalf("provenance paths = %#v, want %#v", gotPaths, wantPaths)
	}
}
